### ISSUE TITLE
Abilities to support web streams under IE8-?

### ISSUE THREAD

**Issue by aleen42** [MattiasBuelens/web-streams-polyfill#125]
I have found that there is some breaking point for the shim under IE8-:

1. The `return` is a reserved keyword of `ReadableStreamAsyncIteratorImpl.prototype.return`.
2. Several places have used `getter`, which cannot be implemented under IE8-.

So the question is whether it is possible to shim under IE8-?

**Comment by jimmywarting** [comment]
Who In The World Uses IE8 still?

**Comment by aleen42** [comment]
😂 Just a technical exploration, after checking some implementations of properties like `ReadableStreamDefaultReader.closed`, I knew it is impossible at all. Thanks for your response.

**Comment by MattiasBuelens** [comment]
I'm sorry, but I'm not going to add support for Internet Explorer 8. The minimum version supported by the polyfill is Internet Explorer 11 (because that's what I have access to), and even *that* is already a stretch.

While it *is* be possible to use bracket notation to define methods named after a reserved keyword (e.g. `ReadableStreamAsyncIteratorImpl.prototype["return"]`), there is absolutely no way to define property getters or setters on non-DOM objects in IE8. Something as innocuous as `ReadableStream.prototype.locked` would already be impossible to implement, and I'd need to add non-standard alternatives such as an `isLocked()` method instead.

If you *really* need to support IE8 in 2023, you're welcome to fork the polyfill and make the necessary changes. But since it will by definition deviate from the Streams standard, I won't merge those changes back into this project.
