### ISSUE TITLE
ReadableStream typing does not match async iterator spec

### ISSUE THREAD

**Issue by jacoblee93** [MattiasBuelens/web-streams-polyfill#141]
The globally declared `Symbol.asyncIterator` property here should be a method, not a property.

https://github.com/MattiasBuelens/web-streams-polyfill/blob/master/dist/types/ts3.6/polyfill.d.ts#L26

vs. 

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/AsyncIterator/@@asyncIterator

This causes subtle downstream typing bugs like this:

```
node_modules/@langchain/core/dist/utils/stream.d.ts:1:18 - error TS2320: Interface 'IterableReadableStreamInterface<T>' cannot simultaneously extend types 'ReadableStream<T>' and 'AsyncGenerator<T, any, unknown>'.
  Named property '[Symbol.asyncIterator]' of types 'ReadableStream<T>' and 'AsyncGenerator<T, any, unknown>' are not identical.
```

See:

https://github.com/openai/openai-node/issues/613
https://github.com/langchain-ai/langchainjs/issues/3793

**Comment by MattiasBuelens** [comment]
Thanks for the report!

The reason I defined it as a property rather than a method was because the spec demands that `ReadableStream.prototype[Symbol.asyncIterator] === ReadableStream.prototype.values`, so I have to do [some trickery](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.3.2/src/lib/readable-stream.ts#L370-L376) to make that work. Unfortunately, I didn't consider that this would be visible in the public type definitions... Sorry about that! I'm working on a fix.

I see that you've decided to switch to Node's native `ReadableStream` implementation in https://github.com/openai/openai-node/pull/614. That's awesome, I'm happy to see streams get more native support! 😁

**Comment by jacoblee93** [comment]
Ah got it - thanks for the context and heads up around that typing!

**Comment by jacoblee93** [comment]
Thank you!
