### ISSUE TITLE
`src` folder is not published on npm but used in sourcemaps

### ISSUE THREAD

**Issue by remorses** [MattiasBuelens/web-streams-polyfill#155]
Stack traces will point to non existent files because src folder is not published on npm

**Comment by MattiasBuelens** [comment]
I'm assuming you're using web-streams-polyfill version 3.x, since I stopped publishing source maps as of version 4.0. (In the future, it would really help if you could specify the exact version when reporting an issue. 😉) 

What sort of problems are you seeing with those source maps? They do contain the full source content, so your debugger should be able to show you those sources. When I load [the polyfill from unpkg.com](https://unpkg.com/web-streams-polyfill@3.3.3/dist/polyfill.js) inside Chrome, I can see all source files just fine: 
![afbeelding](https://github.com/user-attachments/assets/7028a7f9-0fda-4cad-9c17-23a7ed92043e)
