### ISSUE TITLE
Thanks for maintaining! Would like to donate original npm web-streams-polyfill username

### ISSUE THREAD

**Issue by creatorrr** [MattiasBuelens/web-streams-polyfill#2]
Lmk @MattiasBuelens :)

**Comment by creatorrr** [comment]
Also shameless plug for https://pipes.js.org which I am going to start actively maintaining. Any feedback welcome!

**Comment by MattiasBuelens** [comment]
Oh wow, thanks for the offer! And yes, I'd love to take over the `web-streams-polyfill` name on npm. I'll take good care of it! 😄 (FYI: I'm [mattiasbuelens](https://www.npmjs.com/~mattiasbuelens) on npm.)

Good to hear that you're planning to work on Pipes.js. I think it's an awesome set of utility functions, a bit like `lodash` but for streams. 😛 If you need some help or suggestions, feel free to give me a ping. 😉

**Comment by creatorrr** [comment]
Invited you to the npm account. :)

**Comment by MattiasBuelens** [comment]
Thanks! 😄 

I'll investigate whether switching to the new polyfill would be a minor or major version bump for `web-streams-polyfill`. The API should be the same, since both are polyfills for the same streams API. However, I need to look into the differences in `package.json` fields (like `main`, `module` and `browser`) and make sure we don't trip up any module loaders/bundlers (because [I've accidentally done that before](https://github.com/Two-Screen/stable/issues/9)).
