### ISSUE TITLE
Source map warnings

### ISSUE THREAD

**Issue by vincaslt** [MattiasBuelens/web-streams-polyfill#53]
Using this library I'm getting warnings like these in browser console and webpack dev server output. I'm using typescript in my project. Do you know if there's something I could do to prevent these warnings?

```
./node_modules/web-streams-polyfill/dist/polyfill.min.js
Module Warning (from ./node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from 'C:\Users\vinca\Documents\Code\proton-drive\node_modules\web-streams-polyfill\src\lib\abort-signal.ts' file: Error: ENOENT: no such file or directory, open 'C:\Users\vinca\Documents\Code\proton-drive\node_modules\web-streams-polyfill\src\lib\abort-signal.ts'
```

**Comment by vincaslt** [comment]
Seems like npm package doesn't have sources

**Comment by MattiasBuelens** [comment]
Indeed, I don't publish the `src/` directory to npm. I didn't think that's necessary, since the source maps contain all source code themselves? Not really sure what Webpack expects... 😕

**Comment by vincaslt** [comment]
Hmm, you're right, it seems that it could be an issue with my configuration. `SourceMapDevToolPlugin` webpack plugin is throwing those errors, don't know why it tries to look for actual source files when it has sourcemaps already.

**Comment by MattiasBuelens** [comment]
Hmm, `source-map-loader` seems to be doing [some questionable things](https://github.com/webpack-contrib/source-map-loader/blob/v1.0.1/src/index.js#L85-L87), where it still tries to load a file even when it has `sourceContent`. Not really sure what to make of it, or if it's even at all related to this particular issue...

If you have a repository with a reproduction case, I could try have a look at what's going on. Maybe there's a way to fix it in `web-streams-polyfill`, maybe we should file an issue with `source-map-loader`, or maybe I'll just publish `src/` to npm for the next release. 😛

**Comment by vincaslt** [comment]
Yeah, seems like source-map-loader in combination with that plugin is what caused the issue for me. I made a repo where it's reproducible, here are the changes: https://github.com/vincaslt/webpack-starter/commit/267a23eae99d41dc93ac12ad70f49b079e6f6a1b

I based it off of: https://github.com/wbkd/webpack-starter/

**Comment by vincaslt** [comment]
I can have errors be ignored by setting: `exclude: /web-streams-polyfill/,` on source-map-loader for now.

**Comment by MattiasBuelens** [comment]
Hang on, something **is** wrong indeed with the polyfill's source maps! Each entry in the `sourcesContent` array is `null`!  🤯 ([See the file on unpkg.com](https://www.unpkg.com/browse/web-streams-polyfill@2.1.1/dist/polyfill.js.map))

I think I didn't notice at first because I did `git checkout v2.1.1 && npm install`. However, since I already had *newer* versions of Rollup and its plugins installed on `master`, it may not have downgraded them? I just tried it again locally by running `npm ci` instead, and I can now reproduce the broken source maps.

I also tried building the tip of `master` and using that inside of the test project, and that works: the new source map has proper source contents. So you can expect the next release to fix the problem. 🙂

If it's okay for you, I'll wait until the 3.0.0 release to ship this fix. For the time being, you can use your `exclude` workaround. Sorry about the inconvenience!

**Comment by MattiasBuelens** [comment]
Version 3.0.0 has been released, with working source maps this time. 😁
