### ISSUE TITLE
User permission denied for WriteStream function execution in iOS Safari 12.0

### ISSUE THREAD

**Issue by pwob** [MattiasBuelens/web-streams-polyfill#6]
Hello I was testing this polyfill to implement video capture in iOS safari 12.0 but I hit this error:

Unhandled Promise Rejection: NotAllowedError: The request is not allowed by the user agent or the platform in the current context, possibly because the user denied permission.

Do I need to enabled something in the settings or this is not a supported browser?

**Comment by MattiasBuelens** [comment]
I don't think that error is related to this polyfill. There's nothing about streams themselves that would require user permission.

More likely, the error is caused by something else in your code that has to do with capturing video. I'm guessing that you're calling `navigator.mediaDevices.getUserMedia()` to request camera input, but you haven't added a `.catch` callback to handle a failed request. That would result in an unhandled rejection.

I recommend you have a look at [the code sample on MDN](https://developer.mozilla.org/en-US/docs/Web/API/MediaDevices/getUserMedia), or search elsewhere for help. Perhaps [this StackOverflow question](https://stackoverflow.com/q/53483975/1321716) may be helpful?

**Comment by pwob** [comment]
Hmnn that's weird I actually accepted the mic and camera permission, and confirmed that there is a stream incoming. Okay just to be sure Ill check how the audio is being handled as I have a recorder for that separately. Thank you so much!

**Comment by pwob** [comment]
Hi, I found the problem. It is because you cannot autoplay anything in iOS safari. You need the user to interact with anything you want to play before you can play it. Thanks again.
