### ISSUE TITLE
AutoAllocateChunkSize working?

### ISSUE THREAD

**Issue by NeoLegends** [MattiasBuelens/web-streams-polyfill#65]
Hey, we've been having trouble using the `autoAllocateChunkSize` feature. I'm not sure if it's a bug or if it's just our understanding lacking about the inner workings of ReadableStreams.

Please see the following example:

```ts
const source: UnderlyingByteSource = {
  autoAllocateChunkSize: DEFAULT_BUF_SIZE, // 8192
  type: "bytes",

  async pull(controller) {
    if (!controller.byobRequest?.view) {
      throw new TypeError("Missing BYOB request although auto-allocating");
    }

    const buf = controller.byobRequest.view;
    const nRead = await read(path, buf);

    if (nRead > 0) {
      controller.byobRequest.respond(nRead);
    } else {
      controller.close();
    }
  },
  async cancel() {
    await close(path);
  },
};

const stream = new ReadableStream(source, { highWaterMark: 1 });
```

As far as I understand, this should never throw the above type error, because if the stream is used from a default reader, the runtime will allocate the required buffers automatically. We do, however, saw that TypeError being thrown when working with the stream. What could the reason be?

**Comment by MattiasBuelens** [comment]
It looks like the problem is caused by the `{ highWaterMark: 1 }`. If you leave that out, the readable byte stream is constructed with a default high water mark of 0. Thus, the stream will not start pulling from its source *unless* you actually start reading from it (using either a default reader or a BYOB reader), and in that case you will *always* have a BYOB request. (Note that the `autoAllocateChunkSize` feature only has an effect when you're using a default reader, it isn't used when using a BYOB reader or when the stream is filling up its internal queue up to the HWM.)

Usually, it is desirable that a readable byte stream has a HWM of 0. You don't want to pull more data if nobody is reading from it, because then you can almost never use the reader-provided buffer. Why does your use case demand a HWM of 1?

Since this polyfill follows the specification very closely, and this question is more about the semantics of the specification rather than the implementation of the polyfill, you might have more luck filing an issue over at [the specification's repository](https://github.com/whatwg/streams/issues).

**Comment by NeoLegends** [comment]
Oh, perfect. The reason for the highWaterMark: 1 is mostly a limited-knowledge one. I wasn't sure whether 0 would work and thought if one buffer was inflight it'd be fine. I'll try to see if passing no hwm works better for us.

**Comment by NeoLegends** [comment]
Indeed it does. Thanks for the insights into the spec! The documentation is still sometimes a bit sparse around small details like this.

**Comment by MattiasBuelens** [comment]
Indeed, the documentation around readable byte streams is still very limited, mostly due to the fact that it hasn't shipped in any browser yet. While the specification hasn't changed much recently around readable byte streams, I think the API might not yet be ideal and perhaps it might still need to change in the future once browsers start implementing it. 🤷
