### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: reader._closedPromise_resolve is not a function

### ISSUE THREAD

**Issue by RangerMauve** [MattiasBuelens/web-streams-polyfill#66]
Hi, I'm getting an unhandled error even though it seems to be working otherwise.

<details>
```
(node:102333) UnhandledPromiseRejectionWarning: TypeError: reader._closedPromise_resolve is not a function
    at defaultReaderClosedPromiseResolve (/home/mauve/programming/make-fetch/node_modules/web-streams-polyfill/dist/ponyfill.es6.js:261:16)
    at ReadableStreamClose (/home/mauve/programming/make-fetch/node_modules/web-streams-polyfill/dist/ponyfill.es6.js:3092:9)
    at ReadableStreamDefaultControllerClose (/home/mauve/programming/make-fetch/node_modules/web-streams-polyfill/dist/ponyfill.es6.js:2616:13)
    at /home/mauve/programming/make-fetch/node_modules/web-streams-polyfill/dist/ponyfill.es6.js:3527:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:102333) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:102333) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
</details>

This is happening with version 3.0.0 installed from NPM on Node v12.16.2

**Comment by MattiasBuelens** [comment]
That's odd... that shouldn't happen. Thanks for reporting.

Do you have a way to reproduce this problem? A code snippet that I can run, or a repository that I can clone?

**Comment by RangerMauve** [comment]
Thanks for the quick response.

It's happening in my tests in [make-fetch](git@github.com:RangerMauve/make-fetch.git)

- `git clone git@github.com:RangerMauve/make-fetch.git`
- `cd make-fetch`
- Get rid of the `try-catch` wrappr on [this line](https://github.com/RangerMauve/make-fetch/blob/master/index.js#L92)
- `npm i`
- `npm test`

**Comment by MattiasBuelens** [comment]
I managed to reproduce it locally right away. Thanks for the very clear reproduction case! 😄 

When the readable stream closes (through `ReadableStreamClose`), it [calls the close steps](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream.ts#L396) of the pending read request of the async iterator, which [releases the lock](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream/async-iterator.ts#L85). This [rejects the reader's closed promise](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream/generic-reader.ts#L38), which also [clears its resolve and reject callbacks](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream/generic-reader.ts#L78-L79). However, `ReadableStreamClose` then [tries to *resolve* that same reader's closed promise](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream.ts#L401), which fails because we already cleared those callbacks.

The polyfill assumes that we'll only ever try to resolve or reject the closed promise *once*. However, the specification doesn't seem to guarantee that, and your example shows that. So this assumption is incorrect, and the polyfill needs to handle this case. I'll work on a fix as soon as possible. 😉

On a slightly unrelated note: I also noticed that, although the closed promise was still pending, `ReadableStreamReaderGenericRelease` still created a *new* closed promise instead of rejecting the existing one. This is because `ReadableStreamClose` had already [set the stream's state to `"closed"`](https://github.com/MattiasBuelens/web-streams-polyfill/blob/v3.0.0/src/lib/readable-stream.ts#L386) before calling the close steps, which in turn call `ReadableStreamReaderGenericRelease`. I'll investigate the impact of this a bit further, since this might need a spec change. 🕵️‍♂️

**Comment by RangerMauve** [comment]
Jeeze, sounds pretty complex. Hopefully this'll help others in the future.

Is there anything I should do on my end of the code in the meantime? I'm fine with leaving my try-catch hack in there for now.

**Comment by MattiasBuelens** [comment]
It's quite complex, yes. I'm actually amazed something as complicated as this can be triggered with very little code. 😅 

Your try-catch hack should be fine for now. Hopefully you'll be able to remove it after the next patch release. 😄
