### ISSUE TITLE
[question/help] tee:ing a async iterator

### ISSUE THREAD

**Issue by jimmywarting** [MattiasBuelens/web-streams-polyfill#80]
I'm trying to mimic basically what `ReadableStream.prototype.tee` dose but doing so only with the help of pure "async generators" 

The idea is to be isomorphic across using node & whatwg streams and don't have to care of what type of stream it is. or importing one or the other streams into a environment that dose not have the one or the other type of stream... only that it's asyncIterable.

```js
/**
 * @param {ReadableStream | Readable} iterable
 */
function tee (iterable) {
  const source = iterable[Symbol.asyncIterator]()
  let chain = source.next()
  // ...

  return [0, 1].map(async function * () {
    // read from `source|chain`, update the chain
  })
}
```

I was wondering if you have any ideas/pointers on how to build such a function. i was thinking of using something like a promise chain or a mutable object pointing to the next value instead of something like a array buffer that would hold all values like a sink dose to maybe avoid leakage (and also to make the other iterable more GC friendly) but I didn't fully solve it.

I found a similar (sync) solution on SO https://stackoverflow.com/a/46416353/1008999
but it still keeps a references to both tee:ed destinations (the buffers variable) in the `next` function, so it's not so GC friendly...?

**Comment by MattiasBuelens** [comment]
Cool idea! 😁

A few thoughts on buffering:
* With a `ReadableStream`, a consumer can start multiple `read()`s without waiting for the previous read to complete. This is already handled for you by the async generator machinery: calling `next()` again while the async generator is still busy will queue up the call.
* With a `ReadableStream`, a producer can enqueue multiple chunks without waiting for the previous chunks to be read by a consumer. Async generators don't support this: after you `yield` a value, you have to wait until the consumer calls `next()` again before you can yield the next one. For this, you're going to need to manage two buffers (one for each iterator) manually.

The solution from StackOverflow seems like a good starting point. However, with async iterators, you also have to handle the case where `source.next()` was already called but hasn't resolved yet, so it's not as simple as slapping some `async` and `await` keywords on it.

Garbage collection is indeed a concern. For `ReadableStream.tee()`, when one of the streams is cancelled, we make sure not to enqueue any more chunks to it.
* To cancel an async iterator, you use its `return()` method. You can use a `try..finally` inside your async generator to perform cleanup logic for when this happens, so that seems like the ideal place to mark yourself as "cancelled" and discard any buffered chunks.
* Alternatively, you can put the buffers inside a `WeakRef`, and have the two async iterators hold the only strong reference of their respective buffer. When one of the async iterators is no longer used, its buffer can be garbage collected.

I'm thinking:
* Have *two* buffers, one for each async iterator.
* Have a shared read promise, initially `undefined`.
* Each async iterator consists of an infinite loop. In each iteration:
   1. If our buffer contains an element, `shift()` it and yield it.
   2. Otherwise, if we aren't already reading from `source`, create a new promise that calls `source.next()` and stores the result in **both** buffers.
   3. Otherwise, await the current read promise. Afterwards, we're guaranteed to have at least one element in our buffer, which we'll yield in the next iteration. (Okay, well, at least if `next()` didn't return `{ done: true }`. I guess we also need a shared `done` flag... 😅)

I must say, you have sparked my interest. If I find some time this evening, I'll give it a try myself. 😛

**Comment by jimmywarting** [comment]
> Async generators don't support this: after you yield a value, you have to wait until the consumer calls next() again before you can yield the next one

I'm aware of that. i will basically not have a bucket (sink)

> Alternatively, you can put the buffers inside a WeakRef
> Have two buffers, one for each async iterator.

I have been thinking of using WeakRef, but it's so new and more complicated :P 

I hope that i did not have to use two buffers (arrays) that calls shift and push.
if you study quickly/briefly how this two libraries works 
- https://github.com/sindresorhus/yocto-queue
- https://github.com/WebReflection/linkedom/blob/HEAD/deep-dive.md

you will see that the common goal is to have a `Node` that have a "branch" to the next/prev `Node` without a array
if i could implement a similar strategy that only links to the next item then maybe i could have two (tee:ed) iterators that would simply just read from the same object in a "forward" only action

```js
// Encueued or yielded the following values:
// a,b,c,d,e,f

// Would result in something like this:
const branch = {
  value: 'a',
  next: {
    value: 'b',
    next: {
      value: 'c',
      next: promise
    }
  }
}
```

if the tee:ed iterator 1 is on value b and iterator 2 on value c
then a can be GC'ed with ease

The two iterators would basically read from the same source (object) but being on different path

**Comment by jimmywarting** [comment]
Sorry if this is totally unrelated to the stream specification.
It's not really any issue with your source

I just hope i could code golf a lite bit with you since you have worked so much with iterator, generators and streams
Maybe this can lead to some `.tee()` performances/breakthrough that could turn up to be more GC friendly? 🤷‍♂️

**Comment by MattiasBuelens** [comment]
All right, here's my first naive implementation. No optimizations whatsoever, but it can serve as a good starting point. 🙂

(I wrote it in TypeScript. If that bothers you, just run it through `tsc` or the [TypeScript playground](https://www.typescriptlang.org/play) first. 😛)
```typescript
/// <reference lib="es2018.asyncgenerator" />

type Pair<T> = [T, T];

function teeAsyncIterator<T>(iterable: AsyncIterable<T>): [AsyncIterable<T>, AsyncIterable<T>] {
  const source = iterable[Symbol.asyncIterator]();

  const buffers: Pair<T[] | undefined> = [[], []];
  let reading = false;
  let done = false;
  let currentRead: Promise<void>;

  async function next(): Promise<void> {
    reading = true;
    const result = await source.next();
    if (result.done) {
      done = true;
    } else {
      buffers[0]?.push(result.value);
      buffers[1]?.push(result.value);
    }
    reading = false;
  }

  async function* branch(i: 0 | 1): AsyncGenerator<T, undefined, undefined> {
    try {
      while (true) {
        if (buffers[i]!.length) {
          yield buffers[i]!.shift()!;
        } else if (done) {
          return;
        } else {
          if (!reading) {
            currentRead = next();
          }
          await currentRead;
        }
      }
    } finally {
      buffers[i] = undefined;
    }
  }

  return [branch(0), branch(1)];
}
```

**Comment by jimmywarting** [comment]
Cool, closing and moving the discussion to the gist!
